### ISSUE TITLE
Поиск по списку блокирует перемещение по осн.таблице

### ISSUE THREAD

**Issue by BMKasu1** [savushkin-r-d/INER#21]
Поиск по списку выдает ошибку, после которой блокируется перемещение по строкам основной таблицы.

Открываю j:\sbs\balanQQ_ForTEST_210217_2 QQ+.exe (от 17-02-2021)
Документы-Единица себестоимости
Стою на основной таблице.
Поиск по спискам (см.картинку) – «Список продукции» KKOM, Строка поиска=Моц, частичное совпадение, подстрока, по графе,  с текущей, назад
![1111222](https://user-images.githubusercontent.com/82371353/114366920-93a53c00-9b84-11eb-8801-a4a15779db06.png)

Выдает ошибку
 ![111333](https://user-images.githubusercontent.com/82371353/114366958-a15ac180-9b84-11eb-83bf-e55a2671eb56.jpg)

Затем не могу передвинуться в основной таблице с текущей строки на другие (вверх-вниз) – только перемещатся могу по полям текущей строки (влево-вправо).

Попросила Христину проверить этот момент в своей задаче (кадры). Такой же глюк.

**Comment by kostomarovvv** [comment]
Исправлено в загрузочных от 19 августа 2021 и старше.
