### ISSUE TITLE
Проблемы с фильтром

### ISSUE THREAD

**Issue by BMKasu1** [savushkin-r-d/INER#25]
J:\disp\disp.exe    Документы – Маркировка – Товары проммаркировки
![1](https://user-images.githubusercontent.com/82371353/120081890-86a6c280-c0c8-11eb-9503-a7ce45f670dc.jpg)

Состояние (BD_GTIN->PST) в жизни может быть кроме 0,1,2,3 еще и null
 ![2](https://user-images.githubusercontent.com/82371353/120081898-8f979400-c0c8-11eb-9311-0eaf916ae755.jpg)

Ставлю фильтр на Состояния: кроме PST=2(Опубликован) 
 ![3](https://user-images.githubusercontent.com/82371353/120081902-97efcf00-c0c8-11eb-84f8-7bc7fe04abdd.jpg)

Отображаются НЕ ВСЕ СТРОКИ!!!! Показало строки, в которых состояние PST={0,1,3}, а строки, где PST=null вообще не показывает(( на скрине выше выделены желтым
 ![4](https://user-images.githubusercontent.com/82371353/120081909-a1793700-c0c8-11eb-93b7-00e112dfe8e5.jpg)

ПРОБУЮ ПОСТАВИТЬ ФИЛЬТР ИНАЧЕ:
 ![5](https://user-images.githubusercontent.com/82371353/120081912-a9d17200-c0c8-11eb-9cc8-74e988ab9d8e.jpg)

Выдает 2 строки. Только где PST=0. Строки, где PST=null не показаны.
 ![6](https://user-images.githubusercontent.com/82371353/120081917-af2ebc80-c0c8-11eb-802c-29daa1e61cc5.jpg)

ФИЛЬТР НА ВЫЧИСЛЯЕМОЕ ПОЛЕ BD_GTIN->WARN (Хочу увидеть только те строки, где это поле не пусто):
 ![7](https://user-images.githubusercontent.com/82371353/120081922-b6ee6100-c0c8-11eb-9681-56d0ef575631.jpg)

После этого сообщения вообще база напрочь «уходит» с экрана, даже есть нажать Нет. То есть в результате – просто пусто, кроме как закрыть основное окно (таблицу Товары проммаркировки) ничего не помогает.

ФИЛЬТР НА НЕ ПУСТУЮ ДАТУ ТОЖЕ ВЫДАЕТ ОШИБКУ, хотя на фоне правильная выборка виднеется..
 ![8](https://user-images.githubusercontent.com/82371353/120081930-c077c900-c0c8-11eb-861a-0731afd89515.jpg)

**Comment by BMKasu1** [comment]
**ПОХОЖАЯ ПРОБЛЕМА С ФИЛЬТРОМ ДЛЯ ПОДЧИНЕННОЙ БАЗЫ.**
disp Документы - Маркировка - Потребность в КМ (недельная)
![image](https://user-images.githubusercontent.com/82371353/120082282-b3f47000-c0ca-11eb-8c18-287e091bad21.png)

При попытке поставить фильтр на поле Источник (BD_SPOT->FROM) в подчиненной базе  "Список товаров потребн. в КМ" выдает ошибку. Остается только закрыть окно, т.к. повторная установка фильтра или передвижения по основной базе не помогают "воскресить" отображение ее строк.
![image](https://user-images.githubusercontent.com/82371353/120082239-7c85c380-c0ca-11eb-8d9b-85b4b2a25e94.png)

В структуре БД:
![image](https://user-images.githubusercontent.com/82371353/120082406-8fe55e80-c0cb-11eb-8198-147f584e7902.png)

**Comment by kostomarovvv** [comment]
1) Чтобы отфильтровать записи со значением поля, например, PST = Null, нужно в окне установки фильтра (F6) перейти на вкладку "Формула", и там задать условие: `PST is null`, или `PST is not null`

2) Фильтр на вычисляемые поля на SQL-сервере не работает, т.к. SQL-сервер ничего не знает про вычисляемые поля. Такие поля можно фильтровать на стороне клиента с помощью обработчика событий OnFilterRecord

3) Чтобы отфильтровать не пустые даты, нужно сравнить дату с заведомо более ранней датой, например, 1900-01-01

4) Фильтр по подчиненной базе не работал, т.к. имя поля совпадало с зарезервированным словом SQL. В данном случае FROM. Эта ошибка исправлена в версиях загрузочного старше 10.06.2021.
